# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

highlighter: pygments

# Setup
title:               Matt's Blog
tagline:             Matt Hamlin's Blog
url:                 http://matthamlin.me
paginate:            1
baseurl:             ""
keep_files: [index.html, CNAME, css, fonts, images, js, LICENSE.txt, README.txt, resume.html, resume.json, resume.pdf, sass]

pages_list:
  Portfolio: '/Portfolio.html'
  Resume: '/resume.html'
  Archive: '/archive'
  Feed: '/atom.xml'
  Status: '/status.html'


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

#gems
gems: [jekyll-gist, jekyll-paginate]


# About/contact
author:
  name:              Matt Hamlin
  url:               https://twitter.com/immatthamlin
  email:             hamlim@outlook.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
